### ISSUE TITLE
It's an inquiry from a Chinese student

### ISSUE THREAD

**Issue by listener213** [Praneshss/Modeling_of_APUF_Compositions#1]
Dr: hello, I am a college student from China, now the research on the topic of PUF modeling using the python, but I failed to model has been, I the overall train of thought is to calculate the total delay of two road, and in the final output after comparison, then output the response, respectively excitation and response to CSV file,Using 2000 to CRPS, using logistic regression method to attack, the accuracy has been 51%, the reliability of my model is 100% of the ideal state, the bottleneck period, I hope to get your help, or upload your modeling code.
I hope you can take time out of your busy schedule to read my email.I am looking forward to your reply, which will be greatly appreciated!

**Comment by Praneshss** [comment]
Please email your question to ***@***.***
Which PUF are you trying to model?

**Comment by Praneshss** [comment]
Dear Cheng,

I have replied to your email as well. Now I'm posting the reply so that it can benefit others.

I have prepared a tutorial on github for understanding the flow of end-to-end modeling attacks, including parity vector generation. Please see the link below: [Modeling attack tutorial](https://github.com/Praneshss/PUF_Tutorial/blob/main/Modeling_attack_on_APUF_tutorial.ipynb)

Happy attacking.
